# [2776. 转换回调函数为 Promise 函数 🔒](https://2xiao.github.io/leetcode-js/problem/2776.html)

🟠 <font color=#ffb800>Medium</font>&emsp; 🔗&ensp;[`力扣`](https://leetcode.cn/problems/convert-callback-based-function-to-promise-based-function) [`LeetCode`](https://leetcode.com/problems/convert-callback-based-function-to-promise-based-function)

## 题目

Write a function that accepts another function `fn` and converts the callback-
based function into a promise-based function.

The function `fn` takes a callback as its first argument, along with any
additional arguments `args` passed as separate inputs.

The `promisify` function returns a new function that should return a promise.
The promise should resolve with the argument passed as the first parameter of
the callback when the callback is invoked without error, and reject with the
error when the callback is called with an error as the second argument.

The following is an example of a function that could be passed into
`promisify`.

> 
> 
> 
> 
> 
> function sum(callback, a, b) {
> 
>   if (a < 0 || b < 0) {
> 
> > 
> const err = Error('a and b must be positive');
> 
> > 
> callback(undefined, err);
> 
>   } else {
> 
> > 
> callback(a + b);
> 
>   }
> 
> }
> 
> 

This is the equivalent code based on promises:

> 
> 
> 
> 
> 
> async function sum(a, b) {
> 
>   if (a < 0 || b < 0) {
> 
> > 
> throw Error('a and b must be positive');
> 
>   } else {
> 
> > 
> return a + b;
> 
>   }
> 
> }
> 
> 



**Example 1:**

> Input: 
> 
> fn = (callback, a, b, c) => {
> 
> > 
> callback(a * b * c);
> 
> }
> 
> args = [1, 2, 3]
> 
> Output: {"resolved": 6}
> 
> Explanation: 
> 
> const asyncFunc = promisify(fn);
> 
> asyncFunc(1, 2, 3).then(console.log); // 6
> 
> 
> 
> fn is called with a callback as the first argument and args as the rest. The promise based version of fn resolves a value of 6 when called with (1, 2, 3).

**Example 2:**

> Input: 
> 
> fn = (callback, a, b, c) => {
> 
> > 
> callback(a * b * c, "Promise Rejected");
> 
> }
> 
> args = [4, 5, 6]
> 
> Output: {"rejected": "Promise Rejected"}
> 
> Explanation: 
> 
> const asyncFunc = promisify(fn);
> 
> asyncFunc(4, 5, 6).catch(console.log); // "Promise Rejected"
> 
> 
> 
> fn is called with a callback as the first argument and args as the rest. As the second argument, the callback accepts an error message, so when fn is called, the promise is rejected with a error message provided in the callback. Note that it did not matter what was passed as the first argument into the callback.

**Constraints:**

  * `1 <= args.length <= 100`
  * `0 <= args[i] <= 10^4`


## 题目大意

编写一个函数，接受另一个函数 `fn` ，并将基于回调函数的函数转换为基于 Promise 的函数。

`promisify` 函数接受一个函数 `fn` ，`fn` 将回调函数作为其第一个参数，并且还可以接受其他额外的参数。

`promisfy` 返回一个新函数，新函数会返回一个 Promise 对象。当回调函数被成功调用时，新函数返回的 Promise
对象应该使用原始函数的结果进行解析；当回调函数被调用出现错误时，返回的 Promise 对象应该被拒绝并携带错误信息。最终返回的基于 Promise
的函数应该接受额外的参数作为输入。

以下是一个可以传递给 `promisify` 的函数示例：

> 
> 
> 
> 
> 
> function sum(callback, a, b) {
> 
>   if (a < 0 || b < 0) {
> 
> > 
> const err = Error('a and b must be positive');
> 
> > 
> callback(undefined, err);
> 
>   } else {
> 
> > 
> callback(a + b);
> 
>   }
> 
> }
> 
> 

这是基于 Promise 的等效代码：

> 
> 
> 
> 
> 
> async function sum(a, b) {
> 
>   if (a < 0 || b < 0) {
> 
> > 
> throw Error('a and b must be positive');
> 
>   } else {
> 
> > 
> return a + b;
> 
>   }
> 
> }
> 
> 



**示例 1：**

> 
> 
> 
> 
> 
> **输入：**
> 
> fn = (callback, a, b, c) => {
> 
>   return callback(a * b * c);
> 
> }
> 
> args = [1, 2, 3]
> 
> **输出：**{"resolved": 6}
> 
> **解释：**
> 
> const asyncFunc = promisify(fn);
> 
> asyncFunc(1, 2, 3).then(console.log); // 6
> 
> 
> 
> fn 以回调函数作为第一个参数和 args 作为其余参数进行调用。当使用 (1, 2, 3) 调用时，基于 Promise 的 fn 将解析为值 6。
> 
> 

**示例 2：**

> 
> 
> 
> 
> 
> **输入：**
> 
> fn = (callback, a, b, c) => {
> 
>   callback(a * b * c, "Promise Rejected");
> 
> }
> 
> args = [4, 5, 6]
> 
> **输出：**{"rejected": "Promise Rejected"}
> 
> **解释：**
> 
> const asyncFunc = promisify(fn);
> 
> asyncFunc(4, 5, 6).catch(console.log); // "Promise Rejected"
> 
> 
> 
> fn 以回调函数作为第一个参数和 args 作为其余参数进行调用。在回调函数的第二个参数中，接受一个错误消息，因此当调用 fn 时，Promise 被拒绝并携带回调函数中提供的错误消息。请注意，不管将什么作为回调函数的第一个参数传递都无关紧要。
> 
> 



**提示：**

  * `1 <= args.length <= 100`
  * `0 <= args[i] <= 10^4`


## 解题思路

#### 复杂度分析

- **时间复杂度**：`O()`，
- **空间复杂度**：`O()`，

## 代码

```javascript

```